import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import {cookies} from 'next/headers';
import {getPool} from '../lib/db.mjs';
import SignIn from './utils/logout';

const inter = Inter({ subsets: ["latin"] });

const getData = async () => {
  const pool = await getPool();
  const uid = cookies().get('uid');
  if (!uid) return null;
  const res = await pool.query('select username, rating from users where uid = $1',[uid.value]);
  if (res.rows.length === 0) {
    return null;
  } else {
    return res.rows[0];
  }
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getData();
  return (
    <html lang="en">
        <body className={inter.className}>
          <div className="min-h-screen bg-gray-100">
          <header className="bg-white shadow">
            <nav className="container mx-auto px-4 py-3 flex justify-between items-center">
              <div className="font-bold text-lg">
              <Link href="/">Chess Website</Link></div>
              <div className="flex">
                {
                  data?
                  <>
                    <div className="text-gray-600 hover:text-gray-800 mx-2">{data.username}</div>
                    <div className="text-gray-600 hover:text-gray-800 mx-2">{data.rating}</div>
                  </>
                  :
                  <></>
                }
                <Link href="/" className="text-gray-600 hover:text-gray-800 mx-2">
                  Play
                </Link>
                <SignIn username={data?.username} />
                { data?.username ? 
                <Link href={`/profile/${data.username}`} className="text-gray-600 hover:text-gray-800 mx-2">
                  Profile
                </Link> : <></> }
              </div>
            </nav>
          </header>
          {children}
          </div>
        </body>
    </html>
  );
}
